project:
  type: website

website:
  title: "ccc blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cardosoccc
      - icon: twitter
        href: https://twitter.com/cccaio33
format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
