---
title: "post inaugural"
author: "Caio Cargnin Cardoso"
date: "2025-08-30"
categories: [other]
---

Post inaugural!

Você que chegou até aqui, por alguma razão, merece no mínimo uma explicação:

Quem sou eu? E por que esse blog existe?

Pois bem. Meu nome é Caio. Sou Engenheiro de Machine Learning, e moro em Florianópolis/SC, Brasil.

Primeiramente, esse é um blog sobre Inteligência Artificial, Deep Learning e Machine Learning.
Tenho especial interesse no aspecto de Engenharia de Sistemas envolvidos no treinamentos de LLMs, e isso é que mais vai ser falado por aqui.

Resolvi começar esse blog por alguns motivos bem específicos:

- registrar os meus estudos;
- manter um portfolio de projetos pessoais;
- experimentar algumas ideias de forma prática;
- compartilhar conteúdo que possa interessar a mais alguém;
- manter ativa a prática da escrita;

Apesar de ser obcecado pelo assunto, odeio consumir conteúdo produzido por IA.
Basta saber que um texto foi criado por uma LLM pra eu perder completamente o interesse.
Acredito que o texto produzido por um cérebro humano é incomparavelmente superior ao texto desprovido de alma produzido por uma LLM qualquer.
A motivação pra iniciar esse blog tem a ver com isso.

A riqueza da cultura humana escrita depende de continuarmos produzindo conteúdo original.
Não podemos delegar a nossa capacidade criativa à esses meros papagaios estocásticos.
Então a minha parte eu farei.

Após essa breve introdução, a tendência é que alguns posts apareçam por aqui com alguma periodicidade.

Até breve!
